def default_json():
    # 该函数返回一个字典，包含了默认的JSON数据（Flet无法读取到本地JSON文件）
    # 请按照JSON及字典格式填写并格式化。
    var = {
        "File": {
            "White": [
                "诗笺#0",
                "诗笺#1",
                "诗笺#2",
                "诗笺#3",
                "诗笺#4",
                "诗笺#5",
                "诗笺#6",
                "诗笺#7",
                "诗笺#8",
                "诗笺#9",
                "录音笔Alpa",
                "【录音】山风",
                "第七小队徽章",
                "【录音】火锅",
                "【录音】睡眠",
                "【录音】踩雪",
                "两用摩托Trophon",
                "空投小饼干",
                "梆笛",
                "【录音】黄莺亮翅",
                "宿舍钥匙",
                "魇魉角",
                "电磁霰弹枪",
                "鱼篓",
                "【录音】鱼戏",
                "发",
                "【录音】黑洞",
                "【影像】脂球",
                "锦囊",
                "病号服",
                "花柄小刀",
                "【影像】深井",
                "【录音】光",
                "登入权限：土星",
                "0327围剿令",
                "魇皮纸377",
                "冰川美食汇",
                "收容报告·小报",
                "收容报告·红色蝴蝶结",
                "收容报告·陶土 花盆",
                "收容报告·裙底之物",
                "公告·十七的宝藏",
                "鸽子集结号",
                "三尾吉祥鱼",
                "给十七的挑战书",
                "烤 全 鸭",
                "警长证",
                "【影像】塔",
                "【影像】现场勘验报告·夏草",
                "星星的碎片·冬",
                "收音机",
                "【录音】太平鼓",
                "魔术棒",
                "拾荒者令牌",
                "石林地图",
                "【录音】叫花鸡",
                "绿色变异种",
                "【影像】水塔",
                "【录音】晨",
                "五彩石",
                "彩虹绘本",
                "金属臂",
                "苦杏仁",
                "【影像】Fuli Auto Shooter！",
                "巴雷特外壳",
                "Fuli雕像",
                "【影像】巢栖道站",
                "【影像】涂鸦",
                "HQ004班次车票",
                "液压剂",
                "锚",
                "诗笺#10",
                "诗笺#11",
                "【影像】堡垒",
                "重生",
                "破译·望影の 方舟Six",
                "破译·Igallta",
                "旁白：忘忧宫",
                "旁白：奥德修斯港",
                "旁白：克洛诺斯",
                "旁白：奇迹之森",
                "旁白：迷宫尽头",
                "《拉瓦钵的覆灭》",
                "虚妄之匣",
                "艾达的超震动小刀",
                "伯尼丝 的研究笔记",
                "伯尼丝的神奇挎包",
                "萨芙的运动相机",
                "定向绳索",
                "身份证件",
                "真理之珠",
                "窃听器",
                "奥德修斯港出海记录",
                "纸片",
                "【影像】时钟悖论",
                "时钟城第93届ALIGN梅花型拉力 赛",
                "今年过节上春晚",
                "穿越小队少一人",
                "世界上的另个我",
                "亲朋好友齐欢聚",
                "未来降临我身边",
                "破译·最后的音矿",
                "破译·半封信",
                "破译·人偶",
                "破译·委托人",
                "生命之音",
                "摘录· 守护日志·机关枪",
                "诗笺#12·战士",
                "诗笺#13·夜之歌",
                "诗笺#14·橄榄树上",
                "诗笺#15·魔术师",
                "诗笺#16·流浪人",
                "战士·一·马",
                "战士·二·疾驰",
                "战士·三·喜剧",
                "战士·四·冰封",
                "战士·五·起飞",
                "战士·六·人类",
                "诗笺#17 Zer0",
                "Poem M2",
                "Poem 3ere",
                "Poem 4Y0",
                "Poem The 5no",
                "里表舞厅",
                "摘录·碎数研档案·幽蓝国",
                "迷猫",
                "管道迷宫",
                "蝶羽笔",
                "街机游戏《催 眠》",
                "街机游戏《瓶瓶罐罐》",
                "街机游戏《Phigros》",
                "街机游戏《彩虹之战》",
                "镜像之镜",
                "谜题保管所:00096",
                "游戏币",
                "诗笺#18 人·影·世",
                "诗笺#19  天蓝",
                "诗笺#20 戏中",
                "Poem Reimei",
                "破译·Spasmodic",
                "诗笺#21 悲惶",
                "诗笺#22 自由",
                "旅馆房卡",
                "便签板",
                "六色之虹",
                "晚归来",
                "药箱",
                "山荷叶标本",
                "【影像】背叛",
                "布兰达的自述",
                "【录音】霓虹美 食图鉴",
                "尊师古卢",
                "霓虹",
                "校卡",
                "《霓虹之声》宣传单",
                "社团导师名录",
                "课程表",
                "【影像】霓虹观雨",
                "百花教坊",
                "糖绳",
                "【影像】土丘",
                "PhigrOS记录-鸠",
                "PhigrOS记录-吉诺",
                "可能性",
                "路星67-改",
                "诗笺 白马",
                "诗笺 抉择",
                "破译·凌日潮汐",
                "庙会",
                "【影像】月面之海",
                "【录音】穹顶",
                "豌豆食谱合集",
                "公派任务",
                "求职书",
                "豌豆种植记录",
                "求救信",
                "克洛诺斯的鸽子",
                "豆羹",
                "辞职书",
                "罐装雪梨膏",
                "替换数据",
                "破译·《极星卫》彩蛋",
                "莫比乌斯的回信",
                "《极星卫》剧本·序",
                "《极星卫》剧本·一",
                "《极星卫》剧本·二",
                "《极星卫》剧本·三",
                "《极星卫》剧本·四",
                "《极星卫》剧本·五",
                "《极星卫》剧本·六",
                "《极星卫》剧本·七",
                "《极星卫》剧本·八",
                "《极星卫》剧本·九",
                "《极星卫》剧本·十",
                "《极星卫》剧本· 十一",
                "《极星卫》剧本·十二",
                "《极星卫》剧本·十三",
                "《极星卫》剧本·十四",
                "《极星卫》剧本·十五",
                "《极星卫》剧本·十六",
                "《极星卫》剧本·十七",
                "《极星卫》剧本·十八",
                "《极星 卫》剧本·十九",
                "《极星卫》剧本·二十",
                "《极星卫》剧本·二十一",
                "《极星卫》剧本·二十二",
                "《极星卫》剧本·二十三",
                "《极星卫》剧本·二十四",
                "《极星卫》剧本·二十五",
                "《极星卫》 剧本·二十六",
                "《极星卫》剧本·二十七",
                "《极星卫》剧本·二十八",
                "《极星卫》剧本·二十九",
                "《极星卫》剧本·三十",
                "《极星卫》剧本·三十一",
                "《极星卫》剧本·三十二",
                "《极星卫》剧 本·三十三",
                "《极星卫》剧本·三十四",
                "摘录·莫比乌斯工作室日志·一",
                "摘录·莫比乌斯工作室日志·二",
                "摘录·莫比乌斯工作室日志·三",
                "隼的行船记录仪·一",
                "隼的行船记录仪·二",
                "隼的行船记录仪·三",
                "旁白：造主",
                "旁白：心魔",
                "旁白：未来",
                "旁白：黎明",
                "评《杰作的诞生》",
                "【影像】时光的废墟",
                "【影像】哈娜",
                "致信：土星系统无法注册与故障问题",
                "【录音】船 桨",
                "PhigrOS记录：路星67大胜利（￣︶￣）↗",
                "霓虹灯牌",
                "锈色羊角锤",
                "《盗月行》调查报告",
                "旁白：流言",
                "旁白：怪盗",
                "旁白：恍惚",
                "旁白：黑月",
                "旁白: From 1 to 500000",
                "幻梦 之一",
                "幻梦 之二",
                "673：律动星盗乐行事件 亚空间副本",
                "673：律动星盗乐行事件 亚空间副本·线索一",
                "673：律动星盗乐行事件 亚空间副本·线索二",
                "报道：《相机里的真假月亮》",
                "散文：《有关旋律的哲思》",
                "报道：《晒月亮的女孩》",
                "【影像】拍摄者采访记录存档",
                "木质八音盒",
                "【影像】直播录屏",
                "文玩核桃",
                "吉克·莱斯波斯-Year372",
                "报道：《酒吧辩手， 市长想谈谈》",
                "小说：《困在街道中的老人》",
                "帖子：《天桥东！发现天狗！》",
                "【影像】街头的Fuli",
                "量子同步终端",
                "喵喵茶",
                "黑月疗养院员工需知",
                "小熊娃娃",
                "影像带：《洛基的世界》",
                "报道：《洛基的世界影评》",
                "【影像】日蚀之月",
                "波提切利原型机",
                "观察记录：雪",
                "观察记录：像",
                "观察记录：友",
                "观察记录：痕",
                "档案·无相乡调查报告",
                "事件·虹再现",
                "布兰达的感谢信",
                "油画",
                "失效门牌",
                "隔音耳机",
                "黑月疗养院日志",
                "机械手套",
                "报道：《律动星城市监控网现已恢复，失灵原因疑似与月食有关》",
                "报道：《对大众心理学研究的反叛：当他人主宰你的存在》",
                "报道：《神秘黑点与浪漫少女的背后：波提切利相机的秘密》",
            ],
            "Blue": [
                "诗笺#0",
                "诗笺#1",
                "诗笺#2",
                "诗笺#3",
                "诗笺#4",
                "诗笺#5",
                "诗笺#6",
                "诗笺#7",
                "诗笺#8",
                "诗笺#9",
                "录音笔Alpa",
                "【录音】山风",
                "第七小队徽章",
                "【录音】火锅",
                "【录音】睡眠",
                "【录音】踩雪",
                "两用摩托Trophon",
                "空投小饼干",
                "梆笛",
                "【录音】黄莺亮翅",
                "宿舍钥匙",
                "魇魉角",
                "电磁霰弹枪",
                "鱼篓",
                "【录音】鱼戏",
                "发",
                "【录音】黑洞",
                "【影像】脂球",
                "锦囊",
                "病号服",
                "花柄小刀",
                "【影像】深井",
                "【录音】光",
                "登入权限：土星",
                "0327围剿令",
                "魇皮纸377",
                "冰川美食汇",
                "收容报告·小报",
                "收容报告·红色蝴蝶结",
                "收容报告·陶土 花盆",
                "收容报告·裙底之物",
                "公告·十七的宝藏",
                "鸽子集结号",
                "三尾吉祥鱼",
                "给十七的挑战书",
                "烤 全 鸭",
                "警长证",
                "【影像】塔",
                "【影像】现场勘验报告·夏草",
                "星星的碎片·冬",
                "收音机",
                "【录音】太平鼓",
                "魔术棒",
                "拾荒者令牌",
                "石林地图",
                "【录音】叫花鸡",
                "绿色变异种",
                "【影像】水塔",
                "【录音】晨",
                "五彩石",
                "彩虹绘本",
                "金属臂",
                "苦杏仁",
                "【影像】Fuli Auto Shooter！",
                "巴雷特外壳",
                "Fuli雕像",
                "【影像】巢栖道站",
                "【影像】涂鸦",
                "HQ004班次车票",
                "液压剂",
                "锚",
                "诗笺#10",
                "诗笺#11",
                "【影像】堡垒",
                "重生",
                "破译·望影の 方舟Six",
                "破译·Igallta",
                "旁白：忘忧宫",
                "旁白：奥德修斯港",
                "旁白：克洛诺斯",
                "旁白：奇迹之森",
                "旁白：迷宫尽头",
                "《拉瓦钵的覆灭》",
                "虚妄之匣",
                "艾达的超震动小刀",
                "伯尼丝 的研究笔记",
                "伯尼丝的神奇挎包",
                "萨芙的运动相机",
                "定向绳索",
                "身份证件",
                "真理之珠",
                "窃听器",
                "奥德修斯港出海记录",
                "纸片",
                "【影像】时钟悖论",
                "时钟城第93届ALIGN梅花型拉力 赛",
                "今年过节上春晚",
                "穿越小队少一人",
                "世界上的另个我",
                "亲朋好友齐欢聚",
                "未来降临我身边",
                "破译·最后的音矿",
                "破译·半封信",
                "破译·人偶",
                "破译·委托人",
                "生命之音",
                "摘录· 守护日志·机关枪",
                "诗笺#12·战士",
                "诗笺#13·夜之歌",
                "诗笺#14·橄榄树上",
                "诗笺#15·魔术师",
                "诗笺#16·流浪人",
                "战士·一·马",
                "战士·二·疾驰",
                "战士·三·喜剧",
                "战士·四·冰封",
                "战士·五·起飞",
                "战士·六·人类",
                "诗笺#17 Zer0",
                "Poem M2",
                "Poem 3ere",
                "Poem 4Y0",
                "Poem The 5no",
                "里表舞厅",
                "摘录·碎数研档案·幽蓝国",
                "迷猫",
                "管道迷宫",
                "蝶羽笔",
                "街机游戏《催 眠》",
                "街机游戏《瓶瓶罐罐》",
                "街机游戏《Phigros》",
                "街机游戏《彩虹之战》",
                "镜像之镜",
                "谜题保管所:00096",
                "游戏币",
                "诗笺#18 人·影·世",
                "诗笺#19  天蓝",
                "诗笺#20 戏中",
                "Poem Reimei",
                "破译·Spasmodic",
                "诗笺#21 悲惶",
                "诗笺#22 自由",
                "旅馆房卡",
                "便签板",
                "六色之虹",
                "晚归来",
                "药箱",
                "山荷叶标本",
                "【影像】背叛",
                "布兰达的自述",
                "【录音】霓虹美 食图鉴",
                "尊师古卢",
                "霓虹",
                "校卡",
                "《霓虹之声》宣传单",
                "社团导师名录",
                "课程表",
                "【影像】霓虹观雨",
                "百花教坊",
                "糖绳",
                "【影像】土丘",
                "PhigrOS记录-鸠",
                "PhigrOS记录-吉诺",
                "可能性",
                "路星67-改",
                "诗笺 白马",
                "诗笺 抉择",
                "破译·凌日潮汐",
                "庙会",
                "【影像】月面之海",
                "【录音】穹顶",
                "豌豆食谱合集",
                "公派任务",
                "求职书",
                "豌豆种植记录",
                "求救信",
                "克洛诺斯的鸽子",
                "豆羹",
                "辞职书",
                "罐装雪梨膏",
                "替换数据",
                "破译·《极星卫》彩蛋",
                "莫比乌斯的回信",
                "《极星卫》剧本·序",
                "《极星卫》剧本·一",
                "《极星卫》剧本·二",
                "《极星卫》剧本·三",
                "《极星卫》剧本·四",
                "《极星卫》剧本·五",
                "《极星卫》剧本·六",
                "《极星卫》剧本·七",
                "《极星卫》剧本·八",
                "《极星卫》剧本·九",
                "《极星卫》剧本·十",
                "《极星卫》剧本· 十一",
                "《极星卫》剧本·十二",
                "《极星卫》剧本·十三",
                "《极星卫》剧本·十四",
                "《极星卫》剧本·十五",
                "《极星卫》剧本·十六",
                "《极星卫》剧本·十七",
                "《极星卫》剧本·十八",
                "《极星 卫》剧本·十九",
                "《极星卫》剧本·二十",
                "《极星卫》剧本·二十一",
                "《极星卫》剧本·二十二",
                "《极星卫》剧本·二十三",
                "《极星卫》剧本·二十四",
                "《极星卫》剧本·二十五",
                "《极星卫》 剧本·二十六",
                "《极星卫》剧本·二十七",
                "《极星卫》剧本·二十八",
                "《极星卫》剧本·二十九",
                "《极星卫》剧本·三十",
                "《极星卫》剧本·三十一",
                "《极星卫》剧本·三十二",
                "《极星卫》剧 本·三十三",
                "《极星卫》剧本·三十四",
                "摘录·莫比乌斯工作室日志·一",
                "摘录·莫比乌斯工作室日志·二",
                "摘录·莫比乌斯工作室日志·三",
                "隼的行船记录仪·一",
                "隼的行船记录仪·二",
                "隼的行船记录仪·三",
                "旁白：造主",
                "旁白：心魔",
                "旁白：未来",
                "旁白：黎明",
                "评《杰作的诞生》",
                "【影像】时光的废墟",
                "【影像】哈娜",
                "致信：土星系统无法注册与故障问题",
                "【录音】船 桨",
                "PhigrOS记录：路星67大胜利（￣︶￣）↗",
                "霓虹灯牌",
                "锈色羊角锤",
                "《盗月行》调查报告",
                "旁白：流言",
                "旁白：怪盗",
                "旁白：恍惚",
                "旁白：黑月",
                "旁白: From 1 to 500000",
                "幻梦 之一",
                "幻梦 之二",
                "673：律动星盗乐行事件 亚空间副本",
                "673：律动星盗乐行事件 亚空间副本·线索一",
                "673：律动星盗乐行事件 亚空间副本·线索二",
                "报道：《相机里的真假月亮》",
                "散文：《有关旋律的哲思》",
                "报道：《晒月亮的女孩》",
                "【影像】拍摄者采访记录存档",
                "木质八音盒",
                "【影像】直播录屏",
                "文玩核桃",
                "吉克·莱斯波斯-Year372",
                "报道：《酒吧辩手， 市长想谈谈》",
                "小说：《困在街道中的老人》",
                "帖子：《天桥东！发现天狗！》",
                "【影像】街头的Fuli",
                "量子同步终端",
                "喵喵茶",
                "黑月疗养院员工需知",
                "小熊娃娃",
                "影像带：《洛基的世界》",
                "报道：《洛基的世界影评》",
                "【影像】日蚀之月",
                "波提切利原型机",
                "观察记录：雪",
                "观察记录：像",
                "观察记录：友",
                "观察记录：痕",
                "档案·无相乡调查报告",
                "事件·虹再现",
                "布兰达的感谢信",
                "油画",
                "失效门牌",
                "隔音耳机",
                "黑月疗养院日志",
                "机械手套",
                "报道：《律动星城市监控网现已恢复，失灵原因疑似与月食有关》",
                "报道：《对大众心理学研究的反叛：当他人主宰你的存在》",
                "报道：《神秘黑点与浪漫少女的背后：波提切利相机的秘密》",
            ],
            "Purple": [
                "诗笺#0",
                "诗笺#1",
                "诗笺#2",
                "诗笺#3",
                "诗笺#4",
                "诗笺#5",
                "诗笺#6",
                "诗笺#7",
                "诗笺#8",
                "诗笺#9",
                "录音笔Alpa",
                "【录音】山风",
                "第七小队徽章",
                "【录音】火锅",
                "【录音】睡眠",
                "【录音】踩雪",
                "两用摩托Trophon",
                "空投小饼干",
                "梆笛",
                "【录音】黄莺亮翅",
                "宿舍钥匙",
                "魇魉角",
                "电磁霰弹枪",
                "鱼篓",
                "【录音】鱼戏",
                "发",
                "【录音】黑洞",
                "【影像】脂球",
                "锦囊",
                "病号服",
                "花柄小刀",
                "【影像】深井",
                "【录音】光",
                "登入权限：土星",
                "0327围剿令",
                "魇皮纸377",
                "冰川美食汇",
                "收容报告·小报",
                "收容报告·红色蝴蝶结",
                "收容报告·陶土 花盆",
                "收容报告·裙底之物",
                "公告·十七的宝藏",
                "鸽子集结号",
                "三尾吉祥鱼",
                "给十七的挑战书",
                "烤 全 鸭",
                "警长证",
                "【影像】塔",
                "【影像】现场勘验报告·夏草",
                "星星的碎片·冬",
                "收音机",
                "【录音】太平鼓",
                "魔术棒",
                "拾荒者令牌",
                "石林地图",
                "【录音】叫花鸡",
                "绿色变异种",
                "【影像】水塔",
                "【录音】晨",
                "五彩石",
                "彩虹绘本",
                "金属臂",
                "苦杏仁",
                "【影像】Fuli Auto Shooter！",
                "巴雷特外壳",
                "Fuli雕像",
                "【影像】巢栖道站",
                "【影像】涂鸦",
                "HQ004班次车票",
                "液压剂",
                "锚",
                "诗笺#10",
                "诗笺#11",
                "【影像】堡垒",
                "重生",
                "破译·望影の 方舟Six",
                "破译·Igallta",
                "旁白：忘忧宫",
                "旁白：奥德修斯港",
                "旁白：克洛诺斯",
                "旁白：奇迹之森",
                "旁白：迷宫尽头",
                "《拉瓦钵的覆灭》",
                "虚妄之匣",
                "艾达的超震动小刀",
                "伯尼丝 的研究笔记",
                "伯尼丝的神奇挎包",
                "萨芙的运动相机",
                "定向绳索",
                "身份证件",
                "真理之珠",
                "窃听器",
                "奥德修斯港出海记录",
                "纸片",
                "【影像】时钟悖论",
                "时钟城第93届ALIGN梅花型拉力 赛",
                "今年过节上春晚",
                "穿越小队少一人",
                "世界上的另个我",
                "亲朋好友齐欢聚",
                "未来降临我身边",
                "破译·最后的音矿",
                "破译·半封信",
                "破译·人偶",
                "破译·委托人",
                "生命之音",
                "摘录· 守护日志·机关枪",
                "诗笺#12·战士",
                "诗笺#13·夜之歌",
                "诗笺#14·橄榄树上",
                "诗笺#15·魔术师",
                "诗笺#16·流浪人",
                "战士·一·马",
                "战士·二·疾驰",
                "战士·三·喜剧",
                "战士·四·冰封",
                "战士·五·起飞",
                "战士·六·人类",
                "诗笺#17 Zer0",
                "Poem M2",
                "Poem 3ere",
                "Poem 4Y0",
                "Poem The 5no",
                "里表舞厅",
                "摘录·碎数研档案·幽蓝国",
                "迷猫",
                "管道迷宫",
                "蝶羽笔",
                "街机游戏《催 眠》",
                "街机游戏《瓶瓶罐罐》",
                "街机游戏《Phigros》",
                "街机游戏《彩虹之战》",
                "镜像之镜",
                "谜题保管所:00096",
                "游戏币",
                "诗笺#18 人·影·世",
                "诗笺#19  天蓝",
                "诗笺#20 戏中",
                "Poem Reimei",
                "破译·Spasmodic",
                "诗笺#21 悲惶",
                "诗笺#22 自由",
                "旅馆房卡",
                "便签板",
                "六色之虹",
                "晚归来",
                "药箱",
                "山荷叶标本",
                "【影像】背叛",
                "布兰达的自述",
                "【录音】霓虹美 食图鉴",
                "尊师古卢",
                "霓虹",
                "校卡",
                "《霓虹之声》宣传单",
                "社团导师名录",
                "课程表",
                "【影像】霓虹观雨",
                "百花教坊",
                "糖绳",
                "【影像】土丘",
                "PhigrOS记录-鸠",
                "PhigrOS记录-吉诺",
                "可能性",
                "路星67-改",
                "诗笺 白马",
                "诗笺 抉择",
                "破译·凌日潮汐",
                "庙会",
                "【影像】月面之海",
                "【录音】穹顶",
                "豌豆食谱合集",
                "公派任务",
                "求职书",
                "豌豆种植记录",
                "求救信",
                "克洛诺斯的鸽子",
                "豆羹",
                "辞职书",
                "罐装雪梨膏",
                "替换数据",
                "破译·《极星卫》彩蛋",
                "莫比乌斯的回信",
                "《极星卫》剧本·序",
                "《极星卫》剧本·一",
                "《极星卫》剧本·二",
                "《极星卫》剧本·三",
                "《极星卫》剧本·四",
                "《极星卫》剧本·五",
                "《极星卫》剧本·六",
                "《极星卫》剧本·七",
                "《极星卫》剧本·八",
                "《极星卫》剧本·九",
                "《极星卫》剧本·十",
                "《极星卫》剧本· 十一",
                "《极星卫》剧本·十二",
                "《极星卫》剧本·十三",
                "《极星卫》剧本·十四",
                "《极星卫》剧本·十五",
                "《极星卫》剧本·十六",
                "《极星卫》剧本·十七",
                "《极星卫》剧本·十八",
                "《极星 卫》剧本·十九",
                "《极星卫》剧本·二十",
                "《极星卫》剧本·二十一",
                "《极星卫》剧本·二十二",
                "《极星卫》剧本·二十三",
                "《极星卫》剧本·二十四",
                "《极星卫》剧本·二十五",
                "《极星卫》 剧本·二十六",
                "《极星卫》剧本·二十七",
                "《极星卫》剧本·二十八",
                "《极星卫》剧本·二十九",
                "《极星卫》剧本·三十",
                "《极星卫》剧本·三十一",
                "《极星卫》剧本·三十二",
                "《极星卫》剧 本·三十三",
                "《极星卫》剧本·三十四",
                "摘录·莫比乌斯工作室日志·一",
                "摘录·莫比乌斯工作室日志·二",
                "摘录·莫比乌斯工作室日志·三",
                "隼的行船记录仪·一",
                "隼的行船记录仪·二",
                "隼的行船记录仪·三",
                "旁白：造主",
                "旁白：心魔",
                "旁白：未来",
                "旁白：黎明",
                "评《杰作的诞生》",
                "【影像】时光的废墟",
                "【影像】哈娜",
                "致信：土星系统无法注册与故障问题",
                "【录音】船 桨",
                "PhigrOS记录：路星67大胜利（￣︶￣）↗",
                "霓虹灯牌",
                "锈色羊角锤",
                "《盗月行》调查报告",
                "旁白：流言",
                "旁白：怪盗",
                "旁白：恍惚",
                "旁白：黑月",
                "旁白: From 1 to 500000",
                "幻梦 之一",
                "幻梦 之二",
                "673：律动星盗乐行事件 亚空间副本",
                "673：律动星盗乐行事件 亚空间副本·线索一",
                "673：律动星盗乐行事件 亚空间副本·线索二",
                "报道：《相机里的真假月亮》",
                "散文：《有关旋律的哲思》",
                "报道：《晒月亮的女孩》",
                "【影像】拍摄者采访记录存档",
                "木质八音盒",
                "【影像】直播录屏",
                "文玩核桃",
                "吉克·莱斯波斯-Year372",
                "报道：《酒吧辩手， 市长想谈谈》",
                "小说：《困在街道中的老人》",
                "帖子：《天桥东！发现天狗！》",
                "【影像】街头的Fuli",
                "量子同步终端",
                "喵喵茶",
                "黑月疗养院员工需知",
                "小熊娃娃",
                "影像带：《洛基的世界》",
                "报道：《洛基的世界影评》",
                "【影像】日蚀之月",
                "波提切利原型机",
                "观察记录：雪",
                "观察记录：像",
                "观察记录：友",
                "观察记录：痕",
                "档案·无相乡调查报告",
                "事件·虹再现",
                "布兰达的感谢信",
                "油画",
                "失效门牌",
                "隔音耳机",
                "黑月疗养院日志",
                "机械手套",
                "报道：《律动星城市监控网现已恢复，失灵原因疑似与月食有关》",
                "报道：《对大众心理学研究的反叛：当他人主宰你的存在》",
                "报道：《神秘黑点与浪漫少女的背后：波提切利相机的秘密》",
            ],
            "Yellow": ["周边·判定线抱枕"],
        },
        "Data": {
            "White": [262144],
            "Blue": [524288],
            "Purple": [2097152, 4194304, 8388608, 16777216],
            "Yellow": [33554432, 67108864, 134217728],
        },
        "Null": {"White": ["Null"]},
        "Avatar": {
            "Blue": [
                "Glaciaxion (Avatar) ",
                "Credits (Avatar) ",
                "Dlyrotz (Avatar) ",
                "光 (Avatar) ",
                "Winter ↑cube↓ (Avatar) ",
                "Cipher : /2&//<|0 (Avatar) ",
                "混乱-Confusion (Avatar) ",
                "FULi AUTO SHOOTER (Avatar) ",
                "HumaN (Avatar) ",
                "[PRAW] (Avatar) ",
                "Pixel Rebelz1 (Avatar) ",
                "Pixel Rebelz2 (Avatar) ",
                "Pixel Rebelz3 (Avatar) ",
                "Cereris1 (Avatar) ",
                "Cereris2 (Avatar) ",
                "Cereris3 (Avatar) ",
                "Sultan Rage (Avatar) ",
                "Class Memories (Avatar) ",
                "-SURREALISM- (Avatar) ",
                "Bonus Time (Avatar) ",
                "Doppelganger1 (Avatar) ",
                "Doppelganger2 (Avatar) ",
                "もぺもぺ1 (Avatar) ",
                "もぺもぺ2 (Avatar) ",
                "MARENOL (Avatar) ",
                "萤火虫の怨1 (Avatar) ",
                "萤火虫の怨2 (Avatar) ",
                "万吨匿名信 (Avatar) ",
                "风屿 (Avatar) ",
                "Aphasia (Avatar) ",
                "華灯爱1 (Avatar) ",
                "華灯爱2 (Avatar) ",
                "dB doll (Avatar) ",
                "Dash (Avatar) ",
                "云女孩 (Avatar) ",
                "Drop It (Avatar) ",
                "RIPPER (Avatar) ",
                "开心病1 (Avatar) ",
                "开心病2 (Avatar) ",
                "Introduction (Avatar) ",
                "Find_Me (Avatar) ",
                "Sein (Avatar) ",
                "狂喜蘭舞1 (Avatar) ",
                "狂喜蘭舞2 (Avatar) ",
                "Sparkle New Life (Avatar) ",
                "Geopelia 3 -by 何呵 (Avatar) ",
                "Christmas -2019 (Avatar) ",
                "Snow Desert (Avatar) ",
                "Burn (Avatar) ",
                "Feast远东之宴1 (Avatar) ",
                "Feast远东之宴2 (Avatar) ",
                "Feast远东之宴3 (Avatar) ",
                "Feast远东之宴4 (Avatar) ",
                "Feast远东之宴5 (Avatar) ",
                "Feast远东之宴6 (Avatar) ",
                "Feast远东之宴7 (Avatar) ",
                "Feast远东之宴8 (Avatar) ",
                "Feast远东之宴9 (Avatar) ",
                "瓷岁1 (Avatar) ",
                "瓷岁2 (Avatar) ",
                "瓷岁3 (Avatar) ",
                "瓷岁4 (Avatar) ",
                "瓷岁5 (Avatar) ",
                "瓷岁6 (Avatar) ",
                "瓷岁7 (Avatar) ",
                "盏茗1 (Avatar) ",
                "盏茗2 (Avatar) ",
                "盏茗3 (Avatar) ",
                "青芽 (Avatar) ",
                "瓷岁-Special (Avatar) ",
                "盏茗-Special (Avatar) ",
                "青芽-Special (Avatar) ",
                "Xenolith (Avatar) ",
                "Para (Avatar) ",
                "Indelible Scar (Avatar) ",
                "Alkaid (Avatar) ",
                "ShineAfter-鸠-普通 (Avatar) ",
                "ShineAfter-水青-普通 (Avatar) ",
            ],
            "Purple": [
                "Eradication Catastrophe (Avatar) ",
                "Engine x Start!! (melody mix) (Avatar) ",
                "Non-Melodic Ragez (MUG Edit) (Avatar) ",
                "Energy Synergy Matrix1 (Avatar) ",
                "Energy Synergy Matrix2 (Avatar) ",
                "Energy Synergy Matrix3 (Avatar) ",
                "Khronostasis Katharsis (Avatar) ",
                "Geopelia 1 -by cycats (Avatar) ",
                "Geopelia 2 -by cycats (Avatar) ",
                "Engine x Start!! extra 1 -by cycats (Avatar) ",
                "FULi AUTO SHOOTER extra 1 -by cycats (Avatar) ",
                "Non-Melodic Ragez extra 1 -by cycats (Avatar) ",
                "RIPPER extra 1 -by cycats (Avatar) ",
                "RIPPER extra 2 -by 何呵 (Avatar) ",
                "Marenol extra 1 -by 喵n葵 (Avatar) ",
                "云女孩 extra 1 -by 御坂果子 (Avatar) ",
                "Geopelia in WEPLAY -by 海产 (Avatar) ",
                "Feast远东之宴-Special1 (Avatar) ",
                "Feast远东之宴-Special2 (Avatar) ",
                "Artificial Existence (Avatar) ",
                "ShineAfter-鸠-曲绘Ver (Avatar) ",
                "ShineAfter-鸠-Special (Avatar) ",
                "ShineAfter-水青-曲绘Ver (Avatar) ",
                "ShineAfter-水青-Special (Avatar) ",
                "ShineAfter-水青-Special2 (Avatar) ",
                "ShineAfter-鸠和水青-Special (Avatar) ",
            ],
        },
        "Illustration": {
            "White": [
                "Glaciaxion (Illustration) ",
                "Eradication Catastrophe (Illustration) ",
                "Credits (Illustration) ",
                "Dlyrotz (Illustration) ",
                "Engine x Start!! (melody mix) (Illustration) ",
                "光 (Illustration) ",
                "Winter ↑cube↓ (Illustration) ",
                "Cipher : /2&//<|0 (Illustration) ",
                "混乱-Confusion (Illustration) ",
                "FULi AUTO SHOOTER (Illustration) ",
                "HumaN (Illustration) ",
                "[PRAW] (Illustration) ",
                "Pixel Rebelz (Illustration) ",
                "Cereris (Illustration) ",
                "Non-Melodic Ragez (MUG Edit) (Illustration) ",
                "Sultan Rage (Illustration) ",
                "Class Memories (Illustration) ",
                "-SURREALISM- (Illustration) ",
                "Bonus Time (Illustration) ",
                "Energy Synergy Matrix (Illustration) ",
                "NYA!!! (Illustration) ",
                "JunXion\xa0Between\xa0Life\xa0And\xa0Death(VIP\xa0Mix) (Illustration) ",
                "cryout (Illustration) ",
                "Reimei (Illustration) ",
                "尊師 ～The Guru～ (Illustration) ",
                "Spasmodic (Illustration) ",
                "Leave All Behind (Illustration) ",
                "Colorful Days♪ (Illustration) ",
                "micro.wav (Illustration) ",
                "重生 (Illustration) ",
                "NO ONE YES MAN (Illustration) ",
                "望影の方舟Six (Illustration) ",
                "Igallta (Illustration) ",
                "Clock Paradox (Illustration) ",
                "Chronologika (Illustration) ",
                "Nick of Time (Illustration) ",
                "Chronomia (Illustration) ",
                "Chronos Collapse - La Campanella (Illustration) ",
                "Rrhar'il (Illustration) ",
                "Crave Wave (Illustration) ",
                "The Chariot ~REVIIVAL~ (Illustration) ",
                "Luminescence (Illustration) ",
                "Retribution (Illustration) ",
                "DESTRUCTION 3,2,1 (Illustration) ",
                "Distorted Fate (Illustration) ",
                "Ποσειδών (Illustration) ",
                "WATER (Illustration) ",
                "Miracle Forest (VIP Mix) (Illustration) ",
                "MOBILYS (Illustration) ",
                "Lyrith -迷宮リリス- (Illustration) ",
                "Demiurge (Illustration) ",
                "Demonkin (Illustration) ",
                "Re_Nascence (Psystyle Ver.) (Illustration) ",
                "Ark (Illustration) ",
                "After Dawn (Illustration) ",
                "INFiNiTE ENERZY -Overdoze- (Illustration) ",
                "Khalid (Illustration) ",
                "Quantum Hyperspace (Illustration) ",
                "Freaky Undulations ~Noble Knights of Tune~ (Illustration) ",
                "PANIC PARADISE (Illustration) ",
                "Re：End of a Dream (Illustration) ",
                "心の記憶 (Illustration) ",
                "Spotlight (Illustration) ",
                "NightTheater (Illustration) ",
                "Ramification (Illustration) ",
                "Der Richter (Illustration) ",
                "ATHAZA (Illustration) ",
                "Another Me (Illustration) ",
                "mechanted (Illustration) ",
                "life flashes before weeb eyes (Illustration) ",
                "Break Through The Barrier (Illustration) ",
                "Chronostasis (Illustration) ",
                "Infinity Heaven (Illustration) ",
                "Disorder (Illustration) ",
                "CROSS†SOUL (Illustration) ",
                "GOODTEK (Illustration) ",
                "GOODBOUNCE (Illustration) ",
                "GOODWORLD (Illustration) ",
                "GOODFORTUNE (Illustration) ",
                "GOODRAGE (Illustration) ",
                "Initialize (Illustration) ",
                "桜樹街道 (Illustration) ",
                "Get Ready!! (Illustration) ",
                "volcanic (Illustration) ",
                "XING (Illustration) ",
                "Final Step! (Illustration) ",
                "Cthugha (Illustration) ",
                "Time to Night Sky (feat. Lee Yu Jin) (Illustration) ",
                "HAZARD (Illustration) ",
                "Another Me (Illustration) ",
                "Don't Never Around (Illustration) ",
                "RESSiSTANCE (Illustration) ",
                "Apocalypse (Illustration) ",
                "Protoflicker (Illustration) ",
                "Horizon Blue (Illustration) ",
                "You are the Miserable (Illustration) ",
                "Stasis (Illustration) ",
                "Shadow (Illustration) ",
                "心之所向 (Illustration) ",
                "inferior (Illustration) ",
                "盏茗 (Illustration) ",
                "青芽 (Illustration) ",
                "瓷岁 (Illustration) ",
                "Feast远东之宴 (Illustration) ",
                "零號車輛 (Illustration) ",
                "神話 (Illustration) ",
                "El último baile (Illustration) ",
                "Trojan (Illustration) ",
                "Temporal Shifting (Illustration) ",
                "Ad astra per aspera (Illustration) ",
                "A journey to the moonlight (Illustration) ",
                "S.A.T.E.L.L.I.T.E. (Illustration) ",
                "Dance with Silence (Illustration) ",
                "Labyrinth in Kowloon: Walled World (Illustration) ",
                "Compute It With Some Devilish Alcoholic Steampunk Engines (Illustration) ",
                "+ERABY+E CONNEC+10N (Illustration) ",
                "Journey with You (Illustration) ",
                "Secret Illumination (Illustration) ",
                "Inverted World (Illustration) ",
                "月詠に鳴る (Illustration) ",
                "TECHNOPOLIS 2085 (Illustration) ",
                "祈 -我ら神祖と共に歩む者なり- (Illustration) ",
                "ストレイソウル・アラウンド (Illustration) ",
                "Manifold Hypothesis (Illustration) ",
                "K.Moe (VIP) (Illustration) ",
                "Xenolith (Illustration) ",
                "Artificial Existence (Illustration) ",
                "Indelible Scar (Illustration) ",
                "幽世桔梗 (Illustration) ",
                "千紫万紅 (Illustration) ",
                "明鏡烈火 (Illustration) ",
                "Cuvism³ (Illustration) ",
                "iL-Artifact (Illustration) ",
                "a truth seeker -Communication with Utopia will be lost- (Illustration) ",
                "君往何处 (Quo Vadis) (Illustration) ",
                "暗夜苏醒 (REANIMATE) (Illustration) ",
                "黄金之城 (GOLD TOWN) (Illustration) ",
                "双重间谍 (Double Agent) (Illustration) ",
                "幻影鬼魅 (PLEASE) (Illustration) ",
            ]
        },
    }

    return var
